## Local Target Schema Rationale

### Executive Summary
While OpenLitterMap (OLM) provides a robust global crowdsourcing taxonomy for litter collection, raw OLM payloads use a generalized schema that does not natively align with regional waste management policies in British Columbia. To ensure data generated by this project is immediately actionable for local municipal staff, environmental stewards (e.g., Alouette River Mentorship Society - ARMS), and regional waste planners, this application implements an **Automated Ingestion Crosswalk Engine**.

This engine transforms global OpenLitterMap records at build time into a **Localized Metro Vancouver Audit Schema**, bridging the gap between open crowdsourced data and regional policy targets.

---

### Alignment with Local Regulatory & Audit Frameworks

Our localized schema translates raw field observations into four core waste streams modeled after regional bylaws and composition studies:

                  ┌──────────────────────────────────────────────┐
                  │    Localized Metro Vancouver Audit Schema    │
                  └──────────────────────┬───────────────────────┘
                                         │
    ┌───────────────────┬────────────────┴───────────────────┬───────────────────┐
    ▼                   ▼                                    ▼                   ▼

┌──────────────────┐┌──────────────────┐                ┌──────────────────┐┌──────────────────┐
│ Single-Use Items ││ Paper/Compostables│                │ Hazardous Waste  ││ Other Recyclables│
│   (Bylaw Priority)││  (Recyclable/Fiber)│                │  (Bio/Chemical)  ││ (Metal/Glass/Bulk)│
└──────────────────┘└──────────────────┘                └──────────────────┘└──────────────────┘


1. **Single-Use Items (Bylaw Priority)**
   * **Local Framework Alignment:** Direct alignment with **Metro Vancouver's Single-Use Item Reduction Strategy** and municipal single-use bylaws (e.g., City of Vancouver Single-Use Item Reduction Bylaw No. 12566, adopted regionally across member municipalities).
   * **Target Items:** Single-use plastic cups, foam packaging/containers, plastic shopping bags, plastic cutlery, and straws.
   * **Value:** Provides local governments with spatial density metrics to evaluate the real-world efficacy of single-use item bans and fee structures in public spaces.

2. **Paper & Compostable Fibers**
   * **Local Framework Alignment:** Aligns with regional organic and paper diversion goals established in the **Metro Vancouver Solid Waste Management Plan**.
   * **Target Items:** Coffee sleeves, napkins, cardboard packaging, paper bags, and compostable takeout cartons.
   * **Value:** Highlights areas where public recycling/organics infrastructure is failing or underutilized along pedestrian corridors.

3. **Hazardous & Biohazardous Waste**
   * **Local Framework Alignment:** Maps to toxic substance disposal guidelines and environmental contamination risks monitored under **City of Maple Ridge Parks & Street Scene Maintenance Protocols**.
   * **Target Items:** Cigarette butts, vape cartridges, e-waste/batteries, medical waste, and uncontained dog waste.
   * **Value:** Identifies immediate public health risks, fire hazards during dry summer months, and concentrated biohazard zones near environmentally sensitive waterways (e.g., the Alouette River watershed).

4. **Other Recyclables & Bulk Debris**
   * **Local Framework Alignment:** Aligns with standard blue-box collection streams and municipal illegal dumping enforcement regulations (**City of Maple Ridge Bylaw No. 7100-2015**).
   * **Target Items:** Aluminum cans, glass bottles, scrap metal, and abandoned construction debris.
   * **Value:** Assists public works teams in optimizing route schedules for roadside bin servicing and targeted illegal dumping remediation.

---

### Technical & Civic Value

* **Zero-Cost ETL Integration ($0.00 Overhead):** The schema translation runs entirely inside GitHub Actions static build pipelines (`scripts/sync_data.py`), emitting lightweight, pre-categorized GeoJSON features without requiring paid database servers or external GIS software.
* **Seamless Stakeholder Communication:** Converts abstract global tag arrays into intuitive regional metrics (e.g., percentage breakdown of single-use plastics vs. hazardous waste), allowing local advocates to deliver ready-to-use spatial evidence directly to municipal councils and environmental planning committees.
